### ISSUE TITLE
SVM-BPfinder server failed to be connected

### ISSUE THREAD

**Issue by santataRU** [comprna/SVM-BPfinder#1]
Dear SVM-BPfinder developers,

The SVM-BPfinder server failed (http://regulatorygenomics.upf.edu/Software/SVM_BP/). I tried to connect to the website, but got an error message: "This site can’t be reached, regulatorygenomics.upf.edu refused to connect."

Is this server still open to users?

Thanks,

Xiao

**Comment by EduEyras** [comment]
Dear Xiao,

sorry about this. The server is not maintained anymore.
You can use the code available in the github
https://github.com/comprna/SVM-BPfinder
It is easy enough to run in the command line. Please let me know if I can
help with that.
best
Eduardo

**Comment by santataRU** [comment]
Dear Eduardo,

Thank you very much! Is the example fasta file (test_A1CF_intron.fa) available so that I can download and test your code?

Best,

Xiao

**Comment by EduEyras** [comment]
Hi,

yes, it is available in the same GitHub

https://github.com/comprna/SVM-BPfinder/blob/main/test_A1CF_intron.fa

Best

Eduardo

**Comment by santataRU** [comment]
Thank you very much! I tried but failed with the following message, is this script for python2 (not python3)? :
(base) bieniaszlab@Pauls-iMac-2 SVM-BPfinder-main % 
`python svm_bpfinder.py -i test_A1CF_intron.fa -s Hsap -l 100 -d 10 `

  File "/Users/bieniaszlab/Downloads/SVM-BPfinder-main/svm_bpfinder.py", line 63
    print '\t'.join(['seq_id','agez','ss_dist','bp_seq','bp_scr','y_cont','ppt_off','ppt_len','ppt_scr','svm_scr'])
          ^
SyntaxError: invalid syntax

**Comment by santataRU** [comment]
Even with the correct Python version, another issue with SVM-BPfinder is that it only supports Intel CPUs, not Apple M series CPUs. For Mac OS users with M series CPUs, the hope was the SVM-BPfinder web server, which is no longer available.

**Comment by EduEyras** [comment]
Thanks for pointing this out.
It must be the SVM-light library.
I will check whether there is a binary available for the M series or
whether we can compile one ourselves.
Best
Eduardo

**Comment by santataRU** [comment]
Dr. Eyras, Thank you very much!

**Comment by santataRU** [comment]
Hi Eduardo,

I hope you are doing well. With some effort, I compiled SVM-light for macOS
on M series chips. I have also converted the Python 2 scripts to Python 3
scripts using an online converter. Now, SVM-BPfinder can work on the Python
3 platform on Mac computers with M series chips. I have included a link at
the end of this email if you would like to download the modified version of
SVM-BPfinder. I would not mind if you post the modified version on GitHub
for users with macOS on M series chips and those using the Python 3
platform.

Thank you for developing this tool. I am a virologist studying HIV-1 and
host RNA splicing, and I am using your SVM-BPfinder tool to score the
polypyrimidine tract.

Best regards,
Xiao
Link:
https://drive.google.com/file/d/1M6zohdZasOCXF0CjYrQN6atu8ecHszi1/view?usp=sharing

**Comment by EduEyras** [comment]
Thanks a lot Xiao
This is really wonderful!
I'll put it in the github, perhaps a separate repository to make things
more clear.
If you don't mind, I will add a thank you to https://github.com/santataRU
or in any way you prefer
Best
Eduardo

**Comment by santataRU** [comment]
Hi Eduardo,

Thank you for your kindness. I am fine with adding a thank you to
https://github.com/santataRU.

Best regards,

Xiao
